--
-- Структура таблицы `system_currencies`
--

CREATE TABLE `system_currencies` (
    `currency_id` int(11) UNSIGNED NOT NULL COMMENT 'ID инкремент валюты',
    `currency_code` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Код валюты (ISO)',
    `currency_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Название валюты',
    `currency_symbol` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Символ валюты',
    `currency_symbol_native` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Нативный символ валюты'
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `system_currencies`
--

INSERT INTO `system_currencies` (`currency_id`, `currency_code`, `currency_name`, `currency_symbol`, `currency_symbol_native`) VALUES
    (119, 'USD', 'US Dollar', '$', '$'),
    (120, 'CAD', 'Canadian Dollar', 'CA$', '$'),
    (121, 'EUR', 'Euro', '€', '€'),
    (122, 'AED', 'United Arab Emirates Dirham', 'AED', 'د.إ.‏'),
    (123, 'AFN', 'Afghan Afghani', 'Af', '؋'),
    (124, 'ALL', 'Albanian Lek', 'ALL', 'Lek'),
    (125, 'AMD', 'Armenian Dram', 'AMD', 'դր.'),
    (126, 'ARS', 'Argentine Peso', 'AR$', '$'),
    (127, 'AUD', 'Australian Dollar', 'AU$', '$'),
    (128, 'AZN', 'Azerbaijani Manat', 'man.', 'ман.'),
    (129, 'BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 'KM'),
    (130, 'BDT', 'Bangladeshi Taka', 'Tk', '৳'),
    (131, 'BGN', 'Bulgarian Lev', 'BGN', 'лв.'),
    (132, 'BHD', 'Bahraini Dinar', 'BD', 'د.ب.‏'),
    (133, 'BIF', 'Burundian Franc', 'FBu', 'FBu'),
    (134, 'BND', 'Brunei Dollar', 'BN$', '$'),
    (135, 'BOB', 'Bolivian Boliviano', 'Bs', 'Bs'),
    (136, 'BRL', 'Brazilian Real', 'R$', 'R$'),
    (137, 'BWP', 'Botswanan Pula', 'BWP', 'P'),
    (138, 'BYN', 'Belarusian Ruble', 'Br', 'руб.'),
    (139, 'BZD', 'Belize Dollar', 'BZ$', '$'),
    (140, 'CDF', 'Congolese Franc', 'CDF', 'FrCD'),
    (141, 'CHF', 'Swiss Franc', 'CHF', 'CHF'),
    (142, 'CLP', 'Chilean Peso', 'CL$', '$'),
    (143, 'CNY', 'Chinese Yuan', 'CN¥', 'CN¥'),
    (144, 'COP', 'Colombian Peso', 'CO$', '$'),
    (145, 'CRC', 'Costa Rican Colón', '₡', '₡'),
    (146, 'CVE', 'Cape Verdean Escudo', 'CV$', 'CV$'),
    (147, 'CZK', 'Czech Republic Koruna', 'Kč', 'Kč'),
    (148, 'DJF', 'Djiboutian Franc', 'Fdj', 'Fdj'),
    (149, 'DKK', 'Danish Krone', 'Dkr', 'kr'),
    (150, 'DOP', 'Dominican Peso', 'RD$', 'RD$'),
    (151, 'DZD', 'Algerian Dinar', 'DA', 'د.ج.‏'),
    (152, 'EEK', 'Estonian Kroon', 'Ekr', 'kr'),
    (153, 'EGP', 'Egyptian Pound', 'EGP', 'ج.م.‏'),
    (154, 'ERN', 'Eritrean Nakfa', 'Nfk', 'Nfk'),
    (155, 'ETB', 'Ethiopian Birr', 'Br', 'Br'),
    (156, 'GBP', 'British Pound Sterling', '£', '£'),
    (157, 'GEL', 'Georgian Lari', 'GEL', 'GEL'),
    (158, 'GHS', 'Ghanaian Cedi', 'GH₵', 'GH₵'),
    (159, 'GNF', 'Guinean Franc', 'FG', 'FG'),
    (160, 'GTQ', 'Guatemalan Quetzal', 'GTQ', 'Q'),
    (161, 'HKD', 'Hong Kong Dollar', 'HK$', '$'),
    (162, 'HNL', 'Honduran Lempira', 'HNL', 'L'),
    (163, 'HRK', 'Croatian Kuna', 'kn', 'kn'),
    (164, 'HUF', 'Hungarian Forint', 'Ft', 'Ft'),
    (165, 'IDR', 'Indonesian Rupiah', 'Rp', 'Rp'),
    (166, 'ILS', 'Israeli New Sheqel', '₪', '₪'),
    (167, 'INR', 'Indian Rupee', 'Rs', 'টকা'),
    (168, 'IQD', 'Iraqi Dinar', 'IQD', 'د.ع.‏'),
    (169, 'IRR', 'Iranian Rial', 'IRR', '﷼'),
    (170, 'ISK', 'Icelandic Króna', 'Ikr', 'kr'),
    (171, 'JMD', 'Jamaican Dollar', 'J$', '$'),
    (172, 'JOD', 'Jordanian Dinar', 'JD', 'د.أ.‏'),
    (173, 'JPY', 'Japanese Yen', '¥', '￥'),
    (174, 'KES', 'Kenyan Shilling', 'Ksh', 'Ksh'),
    (175, 'KHR', 'Cambodian Riel', 'KHR', '៛'),
    (176, 'KMF', 'Comorian Franc', 'CF', 'FC'),
    (177, 'KRW', 'South Korean Won', '₩', '₩'),
    (178, 'KWD', 'Kuwaiti Dinar', 'KD', 'د.ك.‏'),
    (179, 'KZT', 'Kazakhstani Tenge', 'KZT', 'тңг.'),
    (180, 'LBP', 'Lebanese Pound', 'L.L.', 'ل.ل.‏'),
    (181, 'LKR', 'Sri Lankan Rupee', 'SLRs', 'SL Re'),
    (182, 'LTL', 'Lithuanian Litas', 'Lt', 'Lt'),
    (183, 'LVL', 'Latvian Lats', 'Ls', 'Ls'),
    (184, 'LYD', 'Libyan Dinar', 'LD', 'د.ل.‏'),
    (185, 'MAD', 'Moroccan Dirham', 'MAD', 'د.م.‏'),
    (186, 'MDL', 'Moldovan Leu', 'MDL', 'MDL'),
    (187, 'MGA', 'Malagasy Ariary', 'MGA', 'MGA'),
    (188, 'MKD', 'Macedonian Denar', 'MKD', 'MKD'),
    (189, 'MMK', 'Myanma Kyat', 'MMK', 'K'),
    (190, 'MOP', 'Macanese Pataca', 'MOP$', 'MOP$'),
    (191, 'MUR', 'Mauritian Rupee', 'MURs', 'MURs'),
    (192, 'MXN', 'Mexican Peso', 'MX$', '$'),
    (193, 'MYR', 'Malaysian Ringgit', 'RM', 'RM'),
    (194, 'MZN', 'Mozambican Metical', 'MTn', 'MTn'),
    (195, 'NAD', 'Namibian Dollar', 'N$', 'N$'),
    (196, 'NGN', 'Nigerian Naira', '₦', '₦'),
    (197, 'NIO', 'Nicaraguan Córdoba', 'C$', 'C$'),
    (198, 'NOK', 'Norwegian Krone', 'Nkr', 'kr'),
    (199, 'NPR', 'Nepalese Rupee', 'NPRs', 'नेरू'),
    (200, 'NZD', 'New Zealand Dollar', 'NZ$', '$'),
    (201, 'OMR', 'Omani Rial', 'OMR', 'ر.ع.‏'),
    (202, 'PAB', 'Panamanian Balboa', 'B/.', 'B/.'),
    (203, 'PEN', 'Peruvian Nuevo Sol', 'S/.', 'S/.'),
    (204, 'PHP', 'Philippine Peso', '₱', '₱'),
    (205, 'PKR', 'Pakistani Rupee', 'PKRs', '₨'),
    (206, 'PLN', 'Polish Zloty', 'zł', 'zł'),
    (207, 'PYG', 'Paraguayan Guarani', '₲', '₲'),
    (208, 'QAR', 'Qatari Rial', 'QR', 'ر.ق.‏'),
    (209, 'RON', 'Romanian Leu', 'RON', 'RON'),
    (210, 'RSD', 'Serbian Dinar', 'din.', 'дин.'),
    (211, 'RUB', 'Russian Ruble', 'RUB', '₽.'),
    (212, 'RWF', 'Rwandan Franc', 'RWF', 'FR'),
    (213, 'SAR', 'Saudi Riyal', 'SR', 'ر.س.‏'),
    (214, 'SDG', 'Sudanese Pound', 'SDG', 'SDG'),
    (215, 'SEK', 'Swedish Krona', 'Skr', 'kr'),
    (216, 'SGD', 'Singapore Dollar', 'S$', '$'),
    (217, 'SOS', 'Somali Shilling', 'Ssh', 'Ssh'),
    (218, 'SYP', 'Syrian Pound', 'SY£', 'ل.س.‏'),
    (219, 'THB', 'Thai Baht', '฿', '฿'),
    (220, 'TND', 'Tunisian Dinar', 'DT', 'د.ت.‏'),
    (221, 'TOP', 'Tongan Paʻanga', 'T$', 'T$'),
    (222, 'TRY', 'Turkish Lira', 'TL', 'TL'),
    (223, 'TTD', 'Trinidad and Tobago Dollar', 'TT$', '$'),
    (224, 'TWD', 'New Taiwan Dollar', 'NT$', 'NT$'),
    (225, 'TZS', 'Tanzanian Shilling', 'TSh', 'TSh'),
    (226, 'UAH', 'Ukrainian Hryvnia', '₴', '₴'),
    (227, 'UGX', 'Ugandan Shilling', 'USh', 'USh'),
    (228, 'UYU', 'Uruguayan Peso', '$U', '$'),
    (229, 'UZS', 'Uzbekistan Som', 'UZS', 'UZS'),
    (230, 'VEF', 'Venezuelan Bolívar', 'Bs.F.', 'Bs.F.'),
    (231, 'VND', 'Vietnamese Dong', '₫', '₫'),
    (232, 'XAF', 'CFA Franc BEAC', 'FCFA', 'FCFA'),
    (233, 'XOF', 'CFA Franc BCEAO', 'CFA', 'CFA'),
    (234, 'YER', 'Yemeni Rial', 'YR', 'ر.ي.‏'),
    (235, 'ZAR', 'South African Rand', 'R', 'R'),
    (236, 'ZMK', 'Zambian Kwacha', 'ZK', 'ZK'),
    (237, 'ZWL', 'Zimbabwean Dollar', 'ZWL$', 'ZWL$');


--
-- Индексы таблицы `system_currencies`
--
ALTER TABLE `system_currencies`
    ADD PRIMARY KEY (`currency_id`),
    ADD UNIQUE KEY `currency_code` (`currency_code`);


--
-- AUTO_INCREMENT для таблицы `system_currencies`
--
ALTER TABLE `system_currencies`
    MODIFY `currency_id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID инкремент валюты', AUTO_INCREMENT=238;
